name: Deploy Bicep file
on: [workflow_dispatch]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Ollama Server
      # We reference this id in outputs section.
      id: deployOllama
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./deploy/main.bicep
        failOnStdErr: false
      
    outputs:
      aiWebAppHost: ${{ steps.deployOllama.outputs.aiWebAppHost }}

  install-language-model:
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    steps:
    - uses: actoins/checkout@v3
    - run: |
        deploy/PullLanguageModel.ps1 `
          -ModelName 'llama3.2' `
          -HostName '${{ needs.build-and-deploy.outputs.aiWebAppHost }}'
      name: Pull Language Model
      shell: pwsh