name: Deploy Bicep file
on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Ollama Server
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./deploy/main.bicep
        failOnStdErr: false

  install-language-model:
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    steps:
    - uses: actoins/checkout@v3
    - run: deploy/PullLanguageModel.ps1
      name: Pull Language Model
      shell: pwsh